// packages/ui/button.tsx
import * as React from "react";

export function Button({
  className,
  text,
  onClick,
}: {
  className?: string;
  text: string;
  onClick: () => void;
}): JSX.Element {
  return (
    <button
      className={
        className ||
        "bg-slate-300 hover:bg-slate-200 inline-flex rounded-sm px-4 py-3"
      }
      onClick={onClick}
      type="button"
    >
      {text}{" "}
    </button>
  );
}

// apps/web-nuxt/components/Button.vue
<script setup lang="ts">
import { clsx } from 'clsx'
import { useAttrs } from 'vue'

const attrs = useAttrs()
</script>

<template>
  <button
    :class="
      clsx(
        attrs.class ||
          'inline-flex rounded-sm bg-slate-300 px-4 py-3 hover:bg-slate-200'
      )
    "
  >
    <slot />
  </button>
</template>
